# PaiNaiDee 3D Map - Docker Compose Configuration
# For local development and production deployment

services:
  # Production server
  painaidee-map:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Development server (alternative port)
  painaidee-dev:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

# Networks
networks:
  default:
    driver: bridge

# Volumes for persistent data (if needed)
volumes:
  nginx_cache:
    driver: local